### ISSUE TITLE
Website hangs when log server unavailable using AsyncGelfHttpAppender

### ISSUE THREAD

**Issue by ekirkco** [jjchiw/gelf4net#75] opened 2021-03-03 21:12 UTC
We had a setup issue with our service and noticed whenever it's not functioning properly the website pushing logs hangs for a very long time on each request.  Removing the appender from the list resolves the issue.

**Comment by jjchiw** [comment] 2021-03-03 23:05
Hi

Which appender are you using?

So the issue is when the graylog endpoint (udp, http, amqp) "hangs" the appender blocks the website?

Could you elaborate more?

Thanks

**Comment by jjchiw** [comment] 2021-03-03 23:15
Sorry went directly to the issue's content and didn't read the subject :(

**Comment by jjchiw** [comment] 2021-03-04 09:47
Well I think I have an idea what to tackle and test.

I'll look in the usage of `HttpClient`.

**Comment by ekirkco** [comment] 2021-03-04 14:23
I was assuming it was somehow a threading issue.  Are the logs not shipped
in a separate thread?  Seems like logging should just add to a buffer and
go on its merry way.

**Comment by jjchiw** [comment] 2021-03-04 14:31
That's more the job of how log4net manage how the logs are sent... It seems
an issue in the starve of threads and timeout of the HttpClient, I'll set a
timeout and verify that it only creates one instance, I'll run some tests,
there are 2 more issues concerning HttpAppender but didn't know what to
test and now I'll try with grayling down and see the threads and
connections that are open, during the weekend I'll check it out

**Comment by jjchiw** [comment] 2021-03-09 01:09
Hi.

Ok, I have a solution based on http://apache-logging.6191.n7.nabble.com/Logger-in-ASP-NET-stops-after-a-few-hours-won-t-restart-until-app-is-cycled-td23330.html.

When there is an exception when connecting to graylog server, it will save the next payloads until there is connection again and will send all of them.

It seems to work fine, I'm testing with https://nbomber.com and the webapp it doesn't hang when I stop and start the input. 

So I hope that during the week I'll finish it and let you know.

**Comment by ekirkco** [comment] 2021-03-09 18:07
Cool, thanks!

**Comment by jjchiw** [comment] 2021-03-11 00:18
Hi!

I just pushed the changes if you want to check them out 
https://github.com/jjchiw/gelf4net/tree/refactor-async-appenders-with-queues-and-timeouts

`bufferSize` doesn't behave as it used, now it works this way
```
<!-- Limit of log lines to buffer for async send. Defaults to 1000-->
<!-- If we cannot connect to graylog and the queue reaches the buffersize it will dequeue messages from the queue-->
<bufferSize value="2000" />
 ```
 
 And now we have two new properties for the `Async~Appenders`
 ```   
  <!-- If we have an exception whe connecting to graylog it will wait and enqueue messages and will start again after milliseconds. Default 5000  -->
<retryAfterMilliseconds value="15000" />
<!-- HttpClient Timeout Limit. Default 2000 only AsyncHttpApender  -->
<httpClientTimeoutMilliseconds value="2000" />
```

Didn't push the nuget package, because I've to test in .net framework... will try to do it during the week...

Well, If you could try it before I push the nuget it would be great :)

**Comment by jjchiw** [comment] 2021-03-15 10:25
Hi!

Just pushed the new packages....

Let me know if it fix the issue

Thanks

**Comment by ekirkco** [comment] 2021-03-16 13:38
Hey, sorry about that.  I've been heads down on something.  Seems to work
much better for me though!  Thanks!  Couple questions on it:
1. Is there any way to know it's failing?
2. How does it handle constant failure?  Like, will it just keep growing a
buffer and consuming memory or will it start to discard log lines?

**Comment by jjchiw** [comment] 2021-03-16 20:18
Great!!!

> 1. Is there any way to know it's failing?

We are using `ErrorHandler` from `log4net` https://stackoverflow.com/a/33261606/181766

> 2. How does it handle constant failure?  Like, will it just keep growing a buffer and consuming memory or will it start to discard log lines?

We are keeping the last `<bufferSize value="2000" />`  

So I'll close the issue :)

**Closed by jjchiw** 2021-03-16 20:18 UTC
